export const CONDITION_DESCRIPTIONS: Record<string, string> = {
  blinded: "A blinded creature can't see and automatically fails any ability check that requires sight. Attack rolls against the creature have advantage, and the creature's attack rolls have disadvantage.",
  charmed: "A charmed creature can't attack the charmer or target the charmer with harmful abilities or magical effects. The charmer has advantage on any ability check to interact socially with the creature.",
  deafened: "A deafened creature can't hear and automatically fails any ability check that requires hearing.",
  frightened: "A frightened creature has disadvantage on ability checks and attack rolls while the source of its fear is within line of sight. The creature can't willingly move closer to the source of its fear.",
  grappled: "A grappled creature's speed becomes 0, and it can't benefit from any bonus to its speed. The condition ends if the grappler is incapacitated or if an effect removes the grappled creature from the reach of the grappler.",
  incapacitated: "An incapacitated creature can't take actions or reactions.",
  invisible: "An invisible creature is impossible to see without the aid of magic or a special sense. The creature has advantage on attack rolls, and attack rolls against it have disadvantage.",
  paralyzed: "A paralyzed creature is incapacitated and can't move or speak. The creature automatically fails STR and DEX saving throws. Attack rolls against the creature have advantage. Any attack that hits is a critical hit if the attacker is within 5 feet.",
  petrified: "A petrified creature is transformed into a solid inanimate substance. Its weight increases by a factor of ten, and it ceases aging. The creature is incapacitated, can't move or speak, and is unaware of its surroundings. Attack rolls against it have advantage. It automatically fails STR and DEX saves. It has resistance to all damage and is immune to poison and disease.",
  poisoned: "A poisoned creature has disadvantage on attack rolls and ability checks.",
  prone: "A prone creature's only movement option is to crawl. The creature has disadvantage on attack rolls. An attack roll against the creature has advantage if the attacker is within 5 feet; otherwise, the attack roll has disadvantage.",
  restrained: "A restrained creature's speed becomes 0. Attack rolls against the creature have advantage, and the creature's attack rolls have disadvantage. The creature has disadvantage on DEX saving throws.",
  stunned: "A stunned creature is incapacitated, can't move, and can speak only falteringly. The creature automatically fails STR and DEX saving throws. Attack rolls against the creature have advantage.",
  unconscious: "An unconscious creature is incapacitated, can't move or speak, and is unaware of its surroundings. The creature drops whatever it's holding and falls prone. Attack rolls against the creature have advantage. Any attack that hits is a critical hit if the attacker is within 5 feet.",
  exhaustion: "Exhaustion has multiple levels. Level 1: Disadvantage on ability checks. Level 2: Speed halved. Level 3: Disadvantage on attack rolls and saving throws. Level 4: HP maximum halved. Level 5: Speed reduced to 0. Level 6: Death.",
  downed: "The creature has been knocked to 0 HP and is making death saving throws.",
  dead: "The creature has died.",
  fled: "The creature has fled from the encounter and is no longer in combat.",
  grappling: "This creature is grappling another creature. Its speed is not affected, but it can only move at half speed while dragging the grappled creature.",
  dodging: "Until the start of this creature's next turn, attack rolls against it have disadvantage and it has advantage on DEX saving throws, provided it can see the attacker.",
  hidden: "The creature is hidden. It has advantage on attack rolls against creatures that can't see it. Its position is unknown until it is detected.",
};
