export const CONDITION_DESCRIPTIONS: Record<string, string> = {
  blinded: "- A blinded creature can't see and automatically fails any ability check that requires sight.\n- Attack rolls against the creature have advantage, and the creature's attack rolls have disadvantage.",
  charmed: "- A charmed creature can't attack the charmer or target the charmer with harmful abilities or magical effects.\n- The charmer has advantage on any ability check to interact socially with the creature.",
  deafened: "- A deafened creature can't hear and automatically fails any ability check that requires hearing.",
  frightened: "- A frightened creature has disadvantage on ability checks and attack rolls while the source of its fear is within line of sight.\n- The creature can't willingly move closer to the source of its fear.",
  grappled: "- A grappled creature's speed becomes 0, and it can't benefit from any bonus to its speed.\n- The condition ends if the grappler is incapacitated or if an effect removes the grappled creature from the reach of the grappler.",
  incapacitated: "- An incapacitated creature can't take actions or reactions.",
  invisible: "- An invisible creature is impossible to see without the aid of magic or a special sense.\n- The creature has advantage on attack rolls, and attack rolls against it have disadvantage.",
  paralyzed: "- A paralyzed creature is incapacitated and can't move or speak.\n- The creature automatically fails STR and DEX saving throws.\n- Attack rolls against the creature have advantage.\n- Any attack that hits is a critical hit if the attacker is within 5 feet.",
  petrified: "- A petrified creature is transformed into a solid inanimate substance.\n- Its weight increases by a factor of ten, and it ceases aging.\n- The creature is incapacitated, can't move or speak, and is unaware of its surroundings.\n- Attack rolls against it have advantage.\n- It automatically fails STR and DEX saves.\n- It has resistance to all damage and is immune to poison and disease.",
  poisoned: "- A poisoned creature has disadvantage on attack rolls and ability checks.",
  prone: "- A prone creature's only movement option is to crawl.\n- The creature has disadvantage on attack rolls.\n- An attack roll against the creature has advantage if the attacker is within 5 feet; otherwise, the attack roll has disadvantage.",
  restrained: "- A restrained creature's speed becomes 0.\n- Attack rolls against the creature have advantage, and the creature's attack rolls have disadvantage.\n- The creature has disadvantage on DEX saving throws.",
  stunned: "- A stunned creature is incapacitated, can't move, and can speak only falteringly.\n- The creature automatically fails STR and DEX saving throws.\n- Attack rolls against the creature have advantage.",
  unconscious: "- An unconscious creature is incapacitated, can't move or speak, and is unaware of its surroundings.\n- The creature drops whatever it's holding and falls prone.\n- Attack rolls against the creature have advantage.\n- Any attack that hits is a critical hit if the attacker is within 5 feet.",
  exhaustion: "- Exhaustion has multiple levels.\n  - Level 1: Disadvantage on ability checks.\n  - Level 2: Speed halved.\n  - Level 3: Disadvantage on attack rolls and saving throws.\n  - Level 4: HP maximum halved.\n  - Level 5: Speed reduced to 0.\n  - Level 6: Death.",
  downed: "- The creature has been knocked to 0 HP and is making death saving throws.",
  dead: "- The creature has died.",
  fled: "- The creature has fled from the encounter and is no longer in combat.",
  grappling: "- This creature is grappling another creature.\n- Its speed is not affected, but it can only move at half speed while dragging the grappled creature.",
  dodging: "- Until the start of this creature's next turn, attack rolls against it have disadvantage and it has advantage on DEX saving throws, provided it can see the attacker.",
  hidden: "- The creature is hidden.\n- It has advantage on attack rolls against creatures that can't see it.\n- Its position is unknown until it is detected.",
};
